214: change logo
sfbrigade/intentional-walk-client pull request #216
Opened 2024-12-17 00:44 UTC by yjshin229

- [x] modify text
- [x] modify logo

Logo not in figma or assets folder

2024-12-17 00:47 UTC, yjshin229 commented
I had to pod install to make the app running. 
This modified the podfile.lock. -> seems like it was updating the yoga's SHA automatically.. 
does anyone know why? 
I didn't update pod or RN.

2024-12-18 01:03 UTC, francisli commented
@yjshin229 hmm, my best guess is that version of the package was replaced in the repository for some reason (i.e. security vulnerability, etc), so when you installed it ended up with a different hash. As long as the app continues to function, I think it should be fine. We'll be wanting to upgrade RN and other dependencies soon anyway...

2024-12-18 01:06 UTC, francisli commented
@yjshin229 looks like Kelsie has updated Figma with a new logo... still waiting on final approval, but if you want to drop it in the app to start, I'd export it at 2x size to include in the project...

2025-01-09 03:45 UTC, francisli requested changes
Looks good, although I'm wondering if maybe we should increase the size of the image as its looking a little bit fuzzy on higher res screens- can you try exporting the image at 3x instead of 2x?

2025-01-23 03:21 UTC, francisli approved these changes
Looks good!

2025-01-23 03:21 UTC, merged